import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full m-1 p-4 text-3xl text-black bg-blue-200 text-center">
          Header
        </header>
        {children}
        <footer className="w-full m-1 p-4 text-2xl text-black bg-red-200 text-center">
          Footer
        </footer>
      </body>
    </html>
  );
}
